### ISSUE TITLE
Using ChatBox from advanced peripherals

### ISSUE THREAD

**Issue by Bluemethyst** [ConnorSwis/GPT.lua#2]
So i know this is old but i was wondering if there was a way this could be set up to work in the chat instead, with a keyword like `askgpt` at the start of the chat message and then the chatbox prints the output to the ingame chat instead of the console. I totally understand if you dont have the time to do this, ive tried it myself but im not familiar with how http requests work in lua

**Comment by Bluemethyst** [comment]
I set this up myself and will fork and upload to my github

**Comment by ConnorSwis** [comment]
I'm trying to keep this script within CC. If you'd like to use this code for the chatbox, please do, but it will not be pulled.
Keep up the great work and thank you for engaging :)
